/* eslint-disable no-undef */
// const { Builder, By, Key, until } = require('selenium-webdriver');
// const faker = require('faker');

// const { scrollToElementByXpath } = require('./utils/scroll-to-path');
// const { randomNumber } = require('./utils/random-number');
// const { timeout } = require('./utils/timeout');

// const { institutionUseCase } = require('./features/Institution');

// const start = async () => {
//   await institutionUseCase();
// };

// (async function  example() {
//   let driver = await new Builder().forBrowser('chrome').build();
//   try {
//     await driver.get('http://localhost:3000/users/dashboards/');

//     await driver.findElement(By.xpath("//*[contains(text(),'Institution Management')]")).click();
//     await timeout(1000);
//     await driver.findElement(By.xpath("//a[@class='btn btn-sm btn-outline-primary mr-2']")).click();
//     await timeout(1000);
//     await driver.findElement(By.xpath(`//a[contains(., 'Publish')]`)).click();
//     await timeout(1000);
//     await driver.findElement(By.xpath(`//button[contains(.,'Yes')]`)).click();
//     await timeout(1000);
//     const Input_Draft_Institution = driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[1]/fieldset[@class='form-group']/div/input"));
//     await Input_Draft_Institution.sendKeys(faker.lorem.words());
//     await driver.findElement(By.xpath(`//button[contains(., 'Save Draft')]`)).click();
//     await timeout(1000);
//     await driver.findElement(By.xpath(`//a[@class='btn btn-sm btn-primary mr-2']`)).click();
//     await timeout(1000);
//     await driver.findElement(By.xpath("//a[@class='btn btn-sm btn-outline-primary mr-2']")).click();
//     await timeout(1000);
//     const Input_Draft_Institution_Edit = driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[1]/fieldset[@class='form-group']/div/input"));
//     await Input_Draft_Institution_Edit.sendKeys(faker.lorem.words());
//     await driver.findElement(By.xpath(`//button[@class='btn btn-sm btn-primary btn-circle btn-circle-sm mr-2']`)).click();
//     await timeout(1000);
//     await driver.findElement(By.xpath(`//button[@class='btn btn-sm btn-danger btn-circle btn-circle-sm']`)).click();
//     await timeout(1000);
//     await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     await timeout(1000);
//     await driver.findElement(By.xpath("//a[contains(., 'Publish')]")).click();
//     await timeout(1000);
//     await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     await timeout(1000);
//     await driver.findElement(By.xpath("//a[contains(., 'Create')]")).click();
//     await timeout(1000);
//     await driver.findElement(By.xpath("//a[contains(., 'Publish')]")).click();
//     await timeout(1000);
//     await driver.findElement(By.xpath("//button[contains(.,'Ok')]")).click();
//     await timeout(1000);
//     const Input_Create_Institution = driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[1]/fieldset[@class='form-group']/div/input"));
//     await Input_Create_Institution.sendKeys(faker.lorem.words());
//     await driver.findElement(By.xpath(`//button[@class='btn btn-sm btn-primary btn-circle btn-circle-sm mr-2']`)).click();
//     await timeout(1000);
//     await driver.findElement(By.xpath(`//button[@class='btn btn-sm btn-danger btn-circle btn-circle-sm']`)).click();
//     await timeout(1000);
//     await driver.findElement(By.xpath("//button[contains(.,'Ok')]")).click();
//     await timeout(1000);
//     await driver.findElement(By.xpath("//a[contains(., 'Publish')]")).click();
//     await timeout(1000);
//     await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     await timeout(1000);
//     await driver.findElement(By.xpath(`//button[@data-v-6ce700e9]`)).click();
//     await timeout(1000);
//     await driver.findElement(By.xpath(`//i[@class='fas fa-times']`)).click();
//     await timeout(1000);
//     await driver.findElement(By.xpath(`//button[@data-v-6ce700e9]`)).click();
//     await timeout(1000);
//     const Input_Edit_Institution = driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[1]/fieldset[@class='form-group']/div/input"));
//     await Input_Edit_Institution.sendKeys(faker.lorem.words());
//     await driver.findElement(By.xpath("//button[@class='btn btn-sm btn-primary btn-circle btn-circle-sm mr-2']")).click();
//     await timeout(1000);
//     await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     await timeout(1000);
//     await driver.findElement(By.xpath(`//i[@class='fas fa pl-3 pr-3 text-dark collapsed']`)).click();
//     await timeout(1000);
//     await driver.findElement(By.xpath(`//div[@class='v-switch-core']`)).click();
//     await timeout(1000);
//     await driver.findElement(By.xpath(`//div[@class='v-switch-button']`)).click();
//     await timeout(1000);
//     await driver.findElement(By.xpath(`//a[contains(., 'History Update')]`)).click();
//     await timeout(1000);
//     await driver.findElement(By.xpath(`//i[@class='fas fa-times position-absolute p-3']`)).click();
//     await timeout(1000);
//     await driver.findElement(By.xpath(`//div[@class='row align-items-stretch']`)).click();
//     await timeout(1000);

//     // await driver.findElement(By.xpath("//*[contains(text(),'Action Management')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[@class='btn btn-sm btn-outline-primary mr-2']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//a[contains(., 'Publish')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // const Input_Draft_Action = driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[1]/fieldset[@class='form-group']/div/input"));
//     // await Input_Draft_Action.sendKeys(faker.lorem.words());
//     // await driver.findElement(By.xpath(`//button[contains(., 'Save Draft')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//a[@class='btn btn-sm btn-primary mr-2']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[@class='btn btn-sm btn-outline-primary mr-2']")).click();
//     // await timeout(1000);
//     // const Input_Draft_Action_Edit = driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[1]/fieldset[@class='form-group']/div/input"));
//     // await Input_Draft_Action_Edit.sendKeys(faker.lorem.words());
//     // await driver.findElement(By.xpath(`//button[@class='btn btn-sm btn-primary btn-circle btn-circle-sm mr-2']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[@class='btn btn-sm btn-danger btn-circle btn-circle-sm']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Publish')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Create')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Publish')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//button[contains(.,'Ok')]")).click();
//     // await timeout(1000);
//     // const Input_Create_Action = driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[1]/fieldset[@class='form-group']/div/input"));
//     // await Input_Create_Action.sendKeys(faker.lorem.words());
//     // await driver.findElement(By.xpath(`//button[@class='btn btn-sm btn-primary btn-circle btn-circle-sm mr-2']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[@class='btn btn-sm btn-danger btn-circle btn-circle-sm']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//button[contains(.,'Ok')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Publish')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[@data-v-6b9e86ed]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//i[@class='fas fa-times']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[@data-v-6b9e86ed]`)).click();
//     // await timeout(1000);
//     // const Input_Edit_Action = driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[1]/fieldset[@class='form-group']/div/input"));
//     // await Input_Edit_Action.sendKeys(faker.lorem.words());
//     // await driver.findElement(By.xpath("//button[@class='btn btn-sm btn-primary btn-circle btn-circle-sm mr-2']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//i[@class='fas fa pl-3 pr-3 text-dark collapsed']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//div[@class='v-switch-core']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//div[@class='v-switch-button']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//a[contains(., 'History Update')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//i[@class='fas fa-times position-absolute p-3']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//div[@class='row align-items-stretch']`)).click();
//     // await timeout(1000);

//     // await driver.findElement(By.xpath("//*[contains(text(),'Laws and Regulations Management')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[@class='btn btn-sm btn-outline-primary mr-2']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//a[contains(., 'Publish')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // const Input_Draft_LAR = driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[1]/fieldset[@class='form-group']/div/input"));
//     // await Input_Draft_LAR.sendKeys(faker.lorem.words());
//     // await driver.findElement(By.xpath(`//button[contains(., 'Save Draft')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//a[@class='btn btn-sm btn-primary mr-2']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[@class='btn btn-sm btn-outline-primary mr-2']")).click();
//     // await timeout(1000);
//     // const Input_Draft_Action_LAR = driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[1]/fieldset[@class='form-group']/div/input"));
//     // await Input_Draft_Action_LAR.sendKeys(faker.lorem.words());
//     // await driver.findElement(By.xpath(`//button[@class='btn btn-sm btn-primary btn-circle btn-circle-sm mr-2']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[@class='btn btn-sm btn-danger btn-circle btn-circle-sm']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Publish')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Create')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Publish')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//button[contains(.,'Ok')]")).click();
//     // await timeout(1000);
//     // const Input_Create_LAR = driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[1]/fieldset[@class='form-group']/div/input"));
//     // await Input_Create_LAR.sendKeys(faker.lorem.words());
//     // await driver.findElement(By.xpath(`//button[@class='btn btn-sm btn-primary btn-circle btn-circle-sm mr-2']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[@class='btn btn-sm btn-danger btn-circle btn-circle-sm']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//button[contains(.,'Ok')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Publish')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[@data-v-f208f07c]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//i[@class='fas fa-times']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[@data-v-f208f07c]`)).click();
//     // await timeout(1000);
//     // const Input_Edit_LAR = driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[1]/fieldset[@class='form-group']/div/input"));
//     // await Input_Edit_LAR.sendKeys(faker.lorem.words());
//     // await driver.findElement(By.xpath("//button[@class='btn btn-sm btn-primary btn-circle btn-circle-sm mr-2']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//i[@class='fas fa pl-3 pr-3 text-dark collapsed']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//div[@class='v-switch-core']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//div[@class='v-switch-button']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//a[contains(., 'History Update')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//i[@class='fas fa-times position-absolute p-3']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//div[@class='row align-items-stretch']`)).click();
//     // await timeout(1000);

//     // //Payment Management
//     // await driver.findElement(By.xpath("//*[contains(text(),'Payment Management')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//a[@class='btn btn-sm btn-outline-primary mr-2']`)).click();
//     // await timeout(1000);
//     // const Input_Draft_Payment = driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[1]/fieldset[@class='form-group']/div/input"));
//     // await Input_Draft_Payment.sendKeys(faker.lorem.words());
//     // await driver.findElement(By.xpath("//a[contains(., 'Publish')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(., 'Save Draft')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//*[contains(text(),'Payment Management')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//a[@class='btn btn-sm btn-outline-primary mr-2']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[2]/fieldset[@class='form-group']/div")).click();
//     // await timeout(1000);
//     // const Input_Draft_Customize = driver.findElement(By.xpath(`//input[@class='select2-search__field']`));
//     // await Input_Draft_Customize.sendKeys("Customize");
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[1]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(., 'Confirm')]`)).click();
//     // await timeout(1000);
//     // const Input_Draft_Number = driver.findElement(By.id("formGroupExampleInput"));
//     // await Input_Draft_Number.sendKeys(faker.random.number());
//     // await driver.findElement(By.xpath("//span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(3)}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(., 'Confirm')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Publish')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//a[@class='btn btn-sm btn-outline-primary mr-2']`)).click();
//     // await timeout(1000);
//     // const Input_Draft_Payment1 = driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[1]/fieldset[@class='form-group']/div/input"));
//     // await Input_Draft_Payment1.sendKeys(faker.lorem.words());
//     // await driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[2]/fieldset[@class='form-group']/div")).click();
//     // await timeout(1000);
//     // const Input_Draft_Customize1 = driver.findElement(By.xpath(`//input[@class='select2-search__field']`));
//     // await Input_Draft_Customize1.sendKeys("Customize");
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[1]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//input[@value='other']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(., 'Confirm')]`)).click();
//     // await timeout(1000);
//     // const Input_Draft_Other = driver.findElement(By.xpath(`//input[@placeholder="Enter Other"]`));
//     // await Input_Draft_Other.sendKeys(faker.lorem.word());
//     // await driver.findElement(By.xpath(`//button[contains(., 'Confirm')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[@class='btn btn-sm btn-primary btn-circle btn-circle-sm mr-2']`)).click();
//     // await timeout(2000);
//     // await driver.findElement(By.xpath(`//button[@class='btn btn-sm btn-danger btn-circle btn-circle-sm']`)).click();
//     // await timeout(2000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Publish')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Create')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Publish')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//button[contains(.,'Ok')]")).click();
//     // await timeout(1000);
//     // const Input_Create_Payment = driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[1]/fieldset[@class='form-group']/div/input"));
//     // await Input_Create_Payment.sendKeys(faker.lorem.words());
//     // await driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[2]/fieldset[@class='form-group']/div")).click();
//     // await timeout(1000);
//     // const Input_Create_Customize = driver.findElement(By.xpath(`//input[@class='select2-search__field']`));
//     // await Input_Create_Customize.sendKeys("Customize");
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[1]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(., 'Confirm')]`)).click();
//     // await timeout(1000);
//     // const Input_Create_Number = driver.findElement(By.id("formGroupExampleInput"));
//     // await Input_Create_Number.sendKeys(faker.random.number());
//     // await driver.findElement(By.xpath("//span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(3)}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(., 'Confirm')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Publish')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Create')]")).click();
//     // await timeout(1000);
//     // const Input_Create_Payment1 = driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[1]/fieldset[@class='form-group']/div/input"));
//     // await Input_Create_Payment1.sendKeys(faker.lorem.words());
//     // await driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[2]/fieldset[@class='form-group']/div")).click();
//     // await timeout(1000);
//     // const Input_Create_Customize2 = driver.findElement(By.xpath(`//input[@class='select2-search__field']`));
//     // await Input_Create_Customize2.sendKeys("Customize");
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[1]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//input[@value='other']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(., 'Confirm')]`)).click();
//     // await timeout(1000);
//     // const Input_Create_Other = driver.findElement(By.xpath(`//input[@placeholder="Enter Other"]`));
//     // await Input_Create_Other.sendKeys(faker.lorem.word());
//     // await driver.findElement(By.xpath(`//button[contains(., 'Confirm')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Publish')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Create')]")).click();
//     // await timeout(1000);
//     // const Input_Create_Payment2 = driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[1]/fieldset[@class='form-group']/div/input"));
//     // await Input_Create_Payment2.sendKeys(faker.lorem.words());
//     // await driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[2]/fieldset[@class='form-group']/div")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber()}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Publish')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//button[contains(.,'Ok')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[@data-v-1e1db805]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//i[@class='fas fa-times']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[@data-v-1e1db805]`)).click();
//     // await timeout(1000);
//     // const Input_Edit_Payment = driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[2]/fieldset[@class='form-group']/div/input"));
//     // await Input_Edit_Payment.sendKeys(faker.lorem.words());
//     // await driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[3]/fieldset[@class='form-group']/div")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber()}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[@data-v-1e1db805]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//div[@class='row align-items-stretch']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//div[@class='v-switch-core']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//div[@class='v-switch-button']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//a[contains(., 'History Update')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//i[@class='fas fa-times position-absolute p-3']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//div[@class='row align-items-stretch']`)).click();
//     // await timeout(1000);

//     // //Report Management
//     // await driver.findElement(By.xpath("//*[contains(text(),'Report Management')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//a[@class='btn btn-sm btn-outline-primary mr-2']`)).click();
//     // await timeout(1000);
//     // const Input_Draft_Reportt = driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[1]/fieldset[@class='form-group']/div/input"));
//     // await Input_Draft_Reportt.sendKeys(faker.lorem.words());
//     // await driver.findElement(By.xpath("//a[contains(., 'Publish')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(., 'Save Draft')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//*[contains(text(),'Report Management')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//a[@data-v-a700d8a6]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[2]/fieldset[@class='form-group']/div")).click();
//     // await timeout(1000);
//     // const Input_DraftReport_Customize = driver.findElement(By.xpath(`//input[@class='select2-search__field']`));
//     // await Input_DraftReport_Customize.sendKeys("Customize");
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[1]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(., 'Confirm')]`)).click();
//     // await timeout(1000);
//     // const Input_DraftReport_Number = driver.findElement(By.id("formGroupExampleInput"));
//     // await Input_DraftReport_Number.sendKeys(faker.random.number());
//     // await driver.findElement(By.xpath("//span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(3)}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(., 'Confirm')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Publish')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//a[@class='btn btn-sm btn-outline-primary mr-2']`)).click();
//     // await timeout(1000);
//     // const Input_Draft_Report1 = driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[1]/fieldset[@class='form-group']/div/input"));
//     // await Input_Draft_Report1.sendKeys(faker.lorem.words());
//     // await driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[2]/fieldset[@class='form-group']/div")).click();
//     // await timeout(1000);
//     // const Input_DraftReport_Customize1 = driver.findElement(By.xpath(`//input[@class='select2-search__field']`));
//     // await Input_DraftReport_Customize1.sendKeys("Customize");
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[1]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//input[@value='other']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(., 'Confirm')]`)).click();
//     // await timeout(1000);
//     // const Input_DraftReport_Other = driver.findElement(By.xpath(`//input[@placeholder="Enter Other"]`));
//     // await Input_DraftReport_Other.sendKeys(faker.lorem.word());
//     // await driver.findElement(By.xpath(`//button[contains(., 'Confirm')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[@class='btn btn-sm btn-primary btn-circle btn-circle-sm mr-2']`)).click();
//     // await timeout(2000);
//     // await driver.findElement(By.xpath(`//button[@class='btn btn-sm btn-danger btn-circle btn-circle-sm']`)).click();
//     // await timeout(2000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Publish')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Create')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Publish')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//button[contains(.,'Ok')]")).click();
//     // await timeout(1000);
//     // const Input_Create_Report = driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[1]/fieldset[@class='form-group']/div/input"));
//     // await Input_Create_Report.sendKeys(faker.lorem.words());
//     // await driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[2]/fieldset[@class='form-group']/div")).click();
//     // await timeout(1000);
//     // const Input_CreateReport_Customize = driver.findElement(By.xpath(`//input[@class='select2-search__field']`));
//     // await Input_CreateReport_Customize.sendKeys("Customize");
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[1]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(., 'Confirm')]`)).click();
//     // await timeout(1000);
//     // const Input_CreateReport_Number = driver.findElement(By.id("formGroupExampleInput"));
//     // await Input_CreateReport_Number.sendKeys(faker.random.number());
//     // await driver.findElement(By.xpath("//span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(3)}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(., 'Confirm')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Publish')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Create')]")).click();
//     // await timeout(1000);
//     // const Input_Create_Report1 = driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[1]/fieldset[@class='form-group']/div/input"));
//     // await Input_Create_Report1.sendKeys(faker.lorem.words());
//     // await driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[2]/fieldset[@class='form-group']/div")).click();
//     // await timeout(1000);
//     // const Input_CreateReport_Customize1 = driver.findElement(By.xpath(`//input[@class='select2-search__field']`));
//     // await Input_CreateReport_Customize1.sendKeys("Customize");
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[1]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//input[@value='other']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(., 'Confirm')]`)).click();
//     // await timeout(1000);
//     // const Input_Create_Other1 = driver.findElement(By.xpath(`//input[@placeholder="Enter Other"]`));
//     // await Input_Create_Other1.sendKeys(faker.lorem.word());
//     // await driver.findElement(By.xpath(`//button[contains(., 'Confirm')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Publish')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Create')]")).click();
//     // await timeout(1000);
//     // const Input_Create_Report2 = driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[1]/fieldset[@class='form-group']/div/input"));
//     // await Input_Create_Report2.sendKeys(faker.lorem.words());
//     // await driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[2]/fieldset[@class='form-group']/div")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber()}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Publish')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[@data-v-a700d8a6]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//i[@class='fas fa-times']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[@data-v-a700d8a6]`)).click();
//     // await timeout(1000);
//     // const Input_Edit_Report = driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[2]/fieldset[@class='form-group']/div/input"));
//     // await Input_Edit_Report.sendKeys(faker.lorem.words());
//     // await driver.findElement(By.xpath("//div[@class='row payment-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[3]/fieldset[@class='form-group']/div")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber()}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[@data-v-a700d8a6]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//div[@class='row align-items-stretch']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//div[@class='v-switch-core']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//div[@class='v-switch-button']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//a[contains(., 'History Update')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//i[@class='fas fa-times position-absolute p-3']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//div[@class='row align-items-stretch']`)).click();
//     // await timeout(1000);

//     //Permit/License Management
//     // await driver.findElement(By.xpath("//*[contains(text(),'Permit / License Management')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//a[@class='btn btn-sm btn-outline-primary mr-2']`)).click();
//     // await timeout(1000);
//     // const Input_Draft_PermitLicense = driver.findElement(By.xpath("//div[@class='row permit-license-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[1]/fieldset[@class='form-group']/div/input"));
//     // await Input_Draft_PermitLicense.sendKeys(faker.lorem.words());
//     // await driver.findElement(By.xpath("//a[contains(., 'Publish')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Yes')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(., 'Save Draft')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//*[contains(text(),'Permit / License Management')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//a[@data-v-e47e9954]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//div[@class='row permit-license-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[2]/fieldset[@class='form-group']/div")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(2)}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//div[@class='row permit-license-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[3]/fieldset[@class='form-group']/div")).click();
//     // await timeout(1000);
//     // const Input_CreateReport_Customize1 = driver.findElement(By.xpath(`//input[@class='select2-search__field']`));
//     // await Input_CreateReport_Customize1.sendKeys("Customize");
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[1]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//input[@value='other']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(., 'Confirm')]`)).click();
//     // await timeout(1000);
//     // const Input_Create_Other1 = driver.findElement(By.xpath(`//input[@placeholder="Enter Other"]`));
//     // await Input_Create_Other1.sendKeys(faker.lorem.word());
//     // await driver.findElement(By.xpath(`//button[contains(., 'Confirm')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//div[@class='obligations-contanier mt-2 p-3 d-flex']/div/div/div/fieldset[@class='form-group']/div/div/div/span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(3)}]`)).click();
//     // await timeout(1000);
//     //await driver.findElement(By.xpath("//select[@class='ObligationsUnderPermitLicense_Select_name']")).click();
//     // await driver.findElement(By.xpath("//div[@class='obligations-contanier mt-2 p-3 d-flex']/div/div[1]/div/fieldset[@class='form-group']/div/div/div/span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);

//     // await driver.findElement(By.xpath("//span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(3)}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);

//     // await driver.findElement(By.xpath("//div[@class='obligations-contanier mt-2 p-3 d-flex']/div/div[1]/fieldset[@class='form-group']/div/div/span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);

//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(2)}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);

//     // await driver.findElement(By.xpath("//div[@class='obligations-contanier mt-2 p-3 d-flex']/div/div[2]/fieldset[@class='form-group']/div/div/span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);

//     // await driver.findElement(By.xpath("//div[@class='obligations-contanier mt-2 p-3 d-flex']/div/div[2]/fieldset[@class='form-group']/div/div/span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);

//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(10)}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[contains(., 'Add more')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(2)}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(2)}]`)).click();
//     // await timeout(1000);

// //Origin code

//     // await driver.findElement(By.xpath("//div[@class='obligations-contanier mt-2 p-3 d-flex']/div/div[1]/fieldset[@class='form-group']/div/div/span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);

//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber_permit_license()}]`)).click();
//     // await timeout(1000);

//     // await driver.findElement(By.xpath("//div[@class='obligations-contanier mt-2 p-3 d-flex']/div/div[2]/fieldset[@class='form-group']/div/div/span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);

//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber_permit_license()}]`)).click();
//     // await timeout(1000);

// //Origin code

//     // await driver.findElement(By.xpath(`//button[@class='btn btn-sm btn-primary btn-circle btn-circle-sm mr-2']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[@class='btn btn-sm btn-danger btn-circle btn-circle-sm']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(., 'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[@class='btn btn-sm btn-danger btn-circle btn-circle-sm align-self-center flex-shrink-0 mt-4']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(., 'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Publish')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Create')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Publish')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//button[contains(.,'Ok')]")).click();
//     // await timeout(1000);
//     // const Input_Draft_Report1 = driver.findElement(By.xpath("//div[@class='row permit-license-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[1]/fieldset[@class='form-group']/div/input"));
//     // await Input_Draft_Report1.sendKeys(faker.lorem.words());
//     // await driver.findElement(By.xpath("//span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(2)}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//div[@class='row permit-license-input-row shadow-border bg-white mt-3 mb-2 py-3']/div[3]/fieldset[@class='form-group']/div")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber()}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(2)}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(2)}]`)).click();
//     // await timeout(1000);

//     // await driver.findElement(By.xpath("//div[@class='obligations-contanier mt-2 p-3 d-flex']/div/div[1]/fieldset[@class='form-group']/div/div/span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);

//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber_permit_license()}]`)).click();
//     // await timeout(1000);

//     // await driver.findElement(By.xpath("//div[@class='obligations-contanier mt-2 p-3 d-flex']/div/div[2]/fieldset[@class='form-group']/div/div/span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);

//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber_permit_license()}]`)).click();
//     // await timeout(1000);

//     // await driver.findElement(By.xpath("//a[contains(., 'Publish')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Yes')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//i[@class='fas fa-pen']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//i[@class='fas fa-times']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//i[@class='fas fa-pen']`)).click();
//     // await timeout(1000);
//     // const Input_Request_Doc = driver.findElement(By.xpath(`//textarea[@data-v-b17be0be]`));
//     // await Input_Request_Doc.sendKeys(faker.lorem.paragraph());
//     // await driver.findElement(By.xpath(`//i[@class='fas fa-save']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Yes')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//div[@class='row align-items-stretch']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//div[@class='v-switch-core']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//div[@class='v-switch-button']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//a[contains(., 'History Update')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//i[@class='fas fa-times position-absolute p-3']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//div[@class='row align-items-stretch']`)).click();
//     // await timeout(1000);

//     //MCOL
//     // await driver.findElement(By.xpath("//*[contains(text(),'MCOL Management')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//a[@class='btn btn-sm btn-outline-primary mr-2']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//div[@class='row mcol-input-row shadow-border bg-white mt-3 mb-2 py-3']/div/div/div/fieldset[@class='form-group']/div/div/span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(4)}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//div[@class='row mcol-input-row shadow-border bg-white mt-3 mb-2 py-3']/div/div/div/fieldset[@class='form-group']/div/div/span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(1)}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//div[@class='row mcol-input-row shadow-border bg-white mt-3 mb-2 py-3']/div/div/div/fieldset[@class='form-group']/div/div/span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(1)}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//div[@class='row mcol-input-row shadow-border bg-white mt-3 mb-2 py-3']/div/div/div/fieldset[@class='form-group']/div/div/span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(1)}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//a[contains(., 'Publish')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(., 'Save Draft')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//*[contains(text(),'MCOL')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//a[@class='btn btn-sm btn-outline-primary mr-2']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//div[@class='row mcol-input-row shadow-border bg-white mt-3 mb-2 py-3']/div/div/div/fieldset[@class='form-group']/div/div/div/span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(4)}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//div[@class='row mcol-input-row shadow-border bg-white mt-3 mb-2 py-3']/div/div/div/fieldset[@class='form-group']/div/span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(1)}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//div[@class='row mcol-input-row shadow-border bg-white mt-3 mb-2 py-3']/div/div/div/fieldset[@class='form-group']/div/span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(1)}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//div[@class='row mcol-input-row shadow-border bg-white mt-3 mb-2 py-3']/div/div/div/fieldset[@class='form-group']/div/span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(1)}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//div[@class='row mcol-input-row shadow-border bg-white mt-3 mb-2 py-3']/div/div[1]/div/fieldset[@class='form-group']/div/div/span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(4)}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(4)}]`)).click();
//     // await timeout(1000);
//     // const Input_Section = driver.findElement(By.xpath("//input[@class='form-control']"));
//     // await Input_Section.sendKeys(faker.lorem.words());
//     // const Input_Section1 = driver.findElement(By.xpath("//input[@placeholder='Enter obligations under laws and regulations']"));
//     // await Input_Section1.sendKeys(faker.lorem.words());
//     // await driver.findElement(By.xpath("//span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(4)}]`)).click();
//     // await timeout(1000);
//     // const Input_Regulatory_Sanction = driver.findElement(By.xpath(`//textarea[@data-v-0091a711]`));
//     // await Input_Regulatory_Sanction.sendKeys(faker.lorem.paragraph());
//     // const Input_RequestedDocforPermit = driver.findElement(By.xpath(`//textarea[@placeholder='Enter requested doc for permit approval ']`));
//     // await Input_RequestedDocforPermit.sendKeys(faker.lorem.paragraph());
//     // await driver.findElement(By.xpath("//button[@class='btn btn-sm btn-primary btn-circle btn-circle-sm mr-2']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//button[@class='btn btn-sm btn-danger btn-circle btn-circle-sm']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Publish')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Create')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Publish')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//div[@class='row mcol-input-row shadow-border bg-white mt-3 mb-2 py-3']/div/div/div/fieldset[@class='form-group']/div/span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(4)}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//div[@class='row mcol-input-row shadow-border bg-white mt-3 mb-2 py-3']/div/div/div/fieldset[@class='form-group']/div/span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(1)}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//div[@class='row mcol-input-row shadow-border bg-white mt-3 mb-2 py-3']/div/div/div/fieldset[@class='form-group']/div/span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(1)}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//div[@class='row mcol-input-row shadow-border bg-white mt-3 mb-2 py-3']/div/div/div/fieldset[@class='form-group']/div/span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(1)}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//div[@class='row mcol-input-row shadow-border bg-white mt-3 mb-2 py-3']/div/div[1]/div/fieldset[@class='form-group']/div/div/span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(4)}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(4)}]`)).click();
//     // await timeout(1000);
//     // const Input_Create_Section = driver.findElement(By.xpath("//input[@placeholder='Enter section']"));
//     // await Input_Create_Section.sendKeys(faker.lorem.words());
//     // const Input_Create_Section1 = driver.findElement(By.xpath("//input[@placeholder='Enter obligations under laws and regulations']"));
//     // await Input_Create_Section1.sendKeys(faker.lorem.words());
//     // await driver.findElement(By.xpath("//span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(4)}]`)).click();
//     // await timeout(1000);
//     // const Input_Create_Regulatory_Sanction = driver.findElement(By.xpath(`//textarea[@data-v-0091a711]`));
//     // await Input_Create_Regulatory_Sanction.sendKeys(faker.lorem.paragraph());
//     // const Input_Create_RequestedDocforPermit = driver.findElement(By.xpath(`//textarea[@placeholder='Enter requested doc for permit approval ']`));
//     // await Input_Create_RequestedDocforPermit.sendKeys(faker.lorem.paragraph());
//     // await driver.findElement(By.xpath("//button[@class='btn btn-sm btn-primary btn-circle btn-circle-sm mr-2']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//button[@class='btn btn-sm btn-danger btn-circle btn-circle-sm']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.executeScript(scrollToElementByXpath, "//a[contains(., 'Publish')]");
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Publish')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//i[@class='fas fa-pen']`)).click();
//     // await timeout(1000);
//     // await driver.executeScript(scrollToElementByXpath, "//i[@class='fas fa-times']");
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//i[@class='fas fa-times']`)).click();
//     // await timeout(1000);
//     // await driver.executeScript(scrollToElementByXpath, "//i[@class='fas fa-pen']");
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//i[@class='fas fa-pen']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//div[@class='row mcol-input-row shadow-border bg-white mt-3 mb-2 py-3']/div/div/div/fieldset[@class='form-group']/div/span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(4)}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//div[@class='row mcol-input-row shadow-border bg-white mt-3 mb-2 py-3']/div/div/div/fieldset[@class='form-group']/div/span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(1)}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//div[@class='row mcol-input-row shadow-border bg-white mt-3 mb-2 py-3']/div/div/div/fieldset[@class='form-group']/div/span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(1)}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//div[@class='row mcol-input-row shadow-border bg-white mt-3 mb-2 py-3']/div/div/div/fieldset[@class='form-group']/div/span[@class='select2 select2-container select2-container--bootstrap4']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(1)}]`)).click();
//     // await timeout(1000);
//     // await driver.executeScript(scrollToElementByXpath, "//i[@class='fas fa-save']");
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//i[@class='fas fa-save']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.executeScript(scrollToElementByXpath, "//div[@class='row align-items-stretch']");
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//div[@class='row align-items-stretch']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//div[@class='v-switch-core']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//div[@class='v-switch-button']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//a[contains(., 'History Update')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//i[@class='fas fa-times position-absolute p-3']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//div[@class='row align-items-stretch']`)).click();
//     // await timeout(1000);

//     // await driver.findElement(By.xpath("//a[contains(., 'Set COL')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//div[@class='custom-control custom-checkbox']")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Add COL')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//button[contains(.,'Ok')]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2 select2-container select2-container--bootstrap4']`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath(`//span[@class='select2-results']/ul/li[${randomNumber(1)}]`)).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//a[contains(., 'Add COL')]")).click();
//     // await timeout(1000);
//     // await driver.findElement(By.xpath("//*[contains(text(),'COL Management')]")).click();
//     // await timeout(1000);

//     } finally {
//         driver.takeScreenshot().then(
//             function(image, err) {
//                 require('fs').writeFile('out.png', image, 'base64', function(err) {
//                     console.log(err);
//                 });
//             }
//         );
//     await driver.quit();
//   }
// })();
